### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by holmes-py** [sbernheim4/dotfiles#4]
Sorry to pull this issue here, but
1. Those are some awesome dotfiles.
2. The link to your repo on the site you wrote an article about tmux is dead. 
[Hackernoon customising tmux](https://hackernoon.com/customizing-tmux-b3d2a5050207)
Had to do some OSINT to find this.
Keep up the good work :v:

**Comment by sbernheim4** [comment]
Thanks for opening the issue! I fixed the link on the medium version of the article and I'm hoping it'll propagate to the  hackernoon site. I'm closing this issue as resolved for now.
